theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
scrolloff = 8
cursorline = true
color-modes = true
true-color = true
rulers = [80, 120]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false
git-ignore = true
