[env]

[settings]
# config files with these prefixes will be trusted by default
trusted_config_paths = ['~/Developer/']
# https://mise.jdx.dev/mise-cookbook/python.html#mise-uv
python.uv_venv_auto = true

[tools]
usage = "latest"
uv = "latest"
go = "latest"
bun = "latest"
node = "latest"
rust = "latest"
python = "latest"
